### ISSUE TITLE
Estudar sobre marcadores finduciais e como eles são aplicado para determinação de pose. Ex: AprilTag, Aruco

### ISSUE THREAD

**Issue by brenopmeneses** [ras-ufcg/Braco#4]

**Comment by Fabiom02** [comment]
Segue abaixo o link do documento que contém minhas atividades desenvolvidas do dia 02/05/2023 até o dia 11/05/2023:
https://docs.google.com/document/d/1T_gTfe3r6i10AFTlKU6INDN-Z_RGIlW_Pugg1j_Wlls/edit?usp=sharing

**Comment by brenopmeneses** [comment]
> Segue abaixo o link do documento que contém minhas atividades desenvolvidas do dia 02/05/2023 até o dia 11/05/2023: https://docs.google.com/document/d/1T_gTfe3r6i10AFTlKU6INDN-Z_RGIlW_Pugg1j_Wlls/edit?usp=sharing

@Fabiom02 

- Quais as diferenças entre ArUco e AprilTag?
- Quais são aplicações de marcadores finduciais em projetos semelhantes?
- Por que não foi desenvolvido algum código teste ou de demonstração durante os estudos?
- Foi estudado algo sobre como realizar a calibração de câmeras, após identificar a sua necessidade?
- Com base nas leituras dos códigos do repositório atual do projeto, quais são as funcionalidades disponíveis identificadas?

Essas anotações feitas são suficientes para reportar o que foi feito, recomendo adicionar o texto diretamente aqui, sem a necessidade do link.

Gostei que os links de estudo foram citados, mas como anotações de estudo são insuficientes, não tem definição de nenhum conceito aprendido. Esse tipo de anotação pode ser escrita em um arquivo `.md` no repositório na pasta `/doc` com os demais integrantes contribuindo complementado como forma de facilitar revisões futuras, por vocês ou outros integrantes.

**Comment by gabriel-nazario** [comment]
Resumo do que foi estudado no período entre 03/05 e 11/05 sobre a aplicação de visão computacional na aplicação de um braço robótico:

De inicio apenas foi estudado a aplicação de ArUco em visão computacional.

Para isso foram estudadas as bibliotecas OpenCV, observando as diversidades de aplicação, mas focando na configuração para melhor entender a biblioteca para a aplicação de marcadores, como me foi orientado. 

Segue link de detalhes do OpenCV:

[https://docs.opencv.org/4.x/d9/d6d/tutorial_table_of_content_aruco.html](https://docs.opencv.org/4.x/d9/d6d/tutorial_table_of_content_aruco.html)

- Para a aplicação se faz necessário observar a calibração da câmera para perfeito funcionamento…

Além disso, foi visto superficialmente a aplicação em Raspberry Pi de curiosidade através de leitura de código em repositórios:

- Manipulação da imagem em forma PB
- Processamento da imagem e geração do ambiente
- Posicionamento do cenário - Calibração
- Formas de aplicação de PID com o mapeamento ArUCo

Link de repositório visto para aplicação: 

[https://github.com/diganthp/Image-processing-of-aruco-markers-using-raspberry-pi](https://github.com/diganthp/Image-processing-of-aruco-markers-using-raspberry-pi)

Como objetivos futuros pretendo ler e rodar códigos já feitos para poder entender melhor o funcionamento e a partir disso, manipular com maior facilidade.
