### ISSUE TITLE
Estudar os materiais da página do Notion "Iniciando no Hardware", com foco em entender o funcionamento de um servo e como realizar o controle com precisão, sem a biblioteca Servo.

### ISSUE THREAD

**Issue by brenopmeneses** [ras-ufcg/Braco#5]

**Comment by yallerocha** [comment]
**Projeto PyArm: Relatório Semanal (Yalle Rocha Silva)**
Período: 08/05/2023 a 14/05/2023

**Resumo das Atividades:**

Durante a semana, foquei no código responsável pelo controle dos servos, com ênfase no servomotor da base.

**Lógica Desenvolvida:**

Para desenvolver uma lógica para controlar o braço, eu parti do pressuposto que a função deve receber como parâmetro uma coordenada tridimensional (x, y, z). Visto que o servo motor da base rotaciona na horizontal, desconsiderei a variável que representa a altura e trabalhei apenas com as variáveis (x, y) no espaço vetorial R² para desenvolver o código desse servo. Portanto, eu deveria criar uma função que me retornasse o ângulo entre o ponto de origem e um ponto qualquer no espaço R².

Pesquisando uma forma de fazer isso, cheguei a conclusão de que eu deveria utilizar algum conceito trigonométrico. De início, pensei em utilizar a bissetriz entre o vetor formado por x e o vetor formado por y, mas ela não leva em consideração o ponto de origem. Depois, enquanto eu olhava algumas imagens de círculos trigonométricos, me deparei com uma representação de arco tangente que parecia muito com o que eu precisava, no caso, uma reta entre a origem e um ponto (x, y) com um determinado ângulo, e por isso decidi testar essa ideia.

Fazendo uma rápida pesquisa no Google, descobri que a biblioteca math possui não só uma função que retorna o arco tangente de um valor, mas também uma função que retorna o arco tangente de um par de coordenadas (x, y), chamada “atan2”, o que era justamente o que eu precisava.

Para testar, utilizei o ponto (3, 4) como exemplo e fiz uma comparação entre o ângulo retornado pela função “atan2” e o ângulo que eu obtive no site GeoGebra ao criar uma reta entre a origem e o ponto (3, 4). O resultado foi positivo, uma vez que que os ângulos obtidos foram os mesmos, sendo necessário converter o ângulo retornado pela função “atan2” de radianos para graus.

**Resultados Alcançados:**

- Uma lógica funcional que pode ser utilizada no código de controle do servomotor da base;

**Desafios:**

- Procurar possíveis erros no raciocínio utilizado;

- Testar o código na prática com o braço robótico;

**Comment by jaymestech** [comment]
**Projeto PyArm: Relatório Semanal (Jaymes Soares Ribeiro)**
Período: 08/05/2023 a 14/05/2023

**Resumo das Atividades:**

Entendi o funcionamento dos servo motores, desde as suas partes integradas ao uso dele com código de Arduino

**Lógica Desenvolvida:**

Baseado no que já foi discutido pessoalmente com Breno somado aos vídeos e conteúdos sobre servo motores:

Servo motores vão transformar energia elétrica em energia mecânica, foi mostrado no laboratório em uma folha de papel o rascunho do básico dessa transformação, e seus cálculos embora não seja preciso se aprofundar a tanto nessa etapa.

Diferente de um motor convencional ao ser colocado em uma fonte de energia, o motor normal irá automaticamente girar sem parar, o servo motor com seu controle de potenciômetro, é enviado para o servo motor e diz exatamente a posição (ângulo) que queremos que ele esteja. [esse ângulo varia de 0 a 180 graus], existe a variação de (open loop) que pode passar desse ângulo, porém se perde em precisão.

O data sheet de um servo motor, fornece bastante informação importante sobre o modelo do servo que usamos, como peso suportado, corrente etc.

Podemos dividir um servo motor em várias partes importantes, aqui estão algumas das que foi aprendido com Breno e que será bastante relevante para o progresso do projeto:

- Conexões elétricas: 3 fios, positivo, negativo, e o sinal;

- Motor e suas engrenagens ;

- Placa de circuito;

- Potenciômetro.

A posição do servo é determinado por pulsos , e esses pulsos podem sem vistos através de alguns equipamentos como Breno me mostrou no lab.
Um pulso pequeno faz o arduino virar para a direita e um pulso grande para esquerda.
Um pulso é determinado por 20 milisegundos.

Coloquei em pratica o uso do servomotor sem a biblioteca do servo.h, e notei que será necessário para o futuro do projeto, o uso dos servos sem essa biblioteca, para maior precisão
https://www.tinkercad.com/things/2zc4rnfLigo-funky-leelo/editel?sharecode=keQBGWePIhdxBTL-dM07kpEPL3UBDzZDDYgGo_xUiR8 , nesse exemplo foi usado a biblioteca pois usei 2 servos, meu próximo objetivo é a utilização de vários servos sem a biblioteca,
